# Generated by Django 3.2.2 on 2021-05-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='coin',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='coin',
            field=models.CharField(max_length=64),
        ),
    ]
