# Generated by Django 3.2.1 on 2021-05-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default='BUY', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='units',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
